### ISSUE TITLE
[meta] Code style

### ISSUE THREAD

**Issue by fredgalvao** [AGBrown/pouchdb.d.ts#19]
So, I have a few small contributions to make, but I don't really see what coding style you prefer (if any) and I don't want to disrupt existing code.

Do you have any? Should we create an [`.editorconfig`](http://editorconfig.org/)? Can I follow default VSCode standards?

**Comment by AGBrown** [comment]
:+1: 

I thought I had an `.editorconfig`, but it doesn't seem to be committed. I don't have the original source folder any more, so let's just create a new one. As long as we code in line with the DT conventions  in the [best practices](http://definitelytyped.org/guides/best-practices.html), [contributions](http://definitelytyped.org/guides/contributing.html) and [submissions](http://definitelytyped.org/guides/creating.html) guides that's all that matters. I think default VSCode standards are probably fine.

**Comment by fredgalvao** [comment]
Welp, there is an `.editorconfig` (don't know why I had forgotten about it), but only style for the inner tests were defined. I did it for the main files now.

**Comment by AGBrown** [comment]
Following gitter chat with @fredgalvao this is where we are at. Based on:
- [pouchdb - contributing](https://github.com/pouchdb/pouchdb/blob/master/CONTRIBUTING.md), which links to [felix's node style guide](https://github.com/felixge/node-style-guide#2-spaces-for-indention)
- and [DT - contributing](http://definitelytyped.org/guides/contributing.html) which says
  
  >  When creating a new definition file the author is free to choose either tabs or 4-space indentation (discussion on github)
- and the discussion on DT issue 4211

We prefer tabs, but will stick to 4 spaces at the moment as that's what this repo started out with. However the reason for 2 spaces in the tests folder is to try and allow for folder diffing of the js output files with the actual pouchdb js test files to check that our implementation is correct.

Commits [7ad3e87](https://github.com/fredgalvao/pouchdb.d.ts/commit/7ad3e871ac784338421c409b88659d0be345fc1d) and [3dd57bb](https://github.com/fredgalvao/pouchdb.d.ts/commit/3dd57bbe1ac367883f5d005e30b46c390c480ecc) take care of this, and should be pulled in from the PR soon.

**Comment by AGBrown** [comment]
Fixed with 3f9ed832f765ed484b70c3aa1f17a35bee38f3cd
