### ISSUE TITLE
Rename `Promise` interfaces

### ISSUE THREAD

**Issue by AGBrown** [AGBrown/pouchdb.d.ts#22]
Calling the interfaces for the promise-based overloads `interface Promise` in all the method-grouping modules is confusing. This happened early on because ... well I forget, but it didn't clash with the original `Thenable` so that was ok. Now that we are doing #18, and @fredgalvao has added `GlobalPromise`, it looks like it does need to be corrected:
1. Rename all the `interface Promise` to something sensible
2. Rename `GlobalPromise` to `Promise` to make it more idiomatic

Note, the official line from the pouchdb team is that callbacks are here to stay.

> <kbd>[00:15:12] &lt;nolanlawson</kbd> ohhhh removing callbacks. Not gonna happen. Some people like them better
> <kbd>[00:15:21] &lt;nolanlawson</kbd> I mean, I don't plan on it

**Comment by fredgalvao** [comment]
On the `Rename GlobalPromise to Promise to make it more idiomatic` subject:

Current proposed definition of GlobalPromise is as follows:

``` typescript
/** Merges declaration with another supplied interface to represent a promise object with custom error typings */
interface GlobalPromise<T> extends Promise<T> {
    /** A Promises/A+ `then` implementation */
    then<R>(onFulfilled?: (value: T) => Promise<R> | R, onRejected?: (error: pouchdb.async.Error) => Promise<R> | R): Promise<R>;
    then<R>(onFulfilled?: (value: T) => Promise<R> | R, onRejected?: (error: pouchdb.async.Error) => void): Promise<R>;
    /** `catch` implementation as per the pouchdb example docs */
    catch<R>(onRejected?: (error: pouchdb.async.Error) => Promise<R> | R): Promise<R>;
    catch<R>(onRejected?: (error: pouchdb.async.Error) => void): Promise<R>;
}
```

If we rename it to Promise, we'll follow in these lines:

### Not compile

``` typescript
interface Promise<T> extends Promise<T> {pouchCode;}
```

 === circular dependency.

We then could simply output definitions to the same global interface that already exists (we hope it does), have typescript merge them all, and then we:

### Mess up third party promises code analysis and completion

By doing this:

``` typescript
interface Promise<T> {pouchCode;}
```

And having `var p:Promise = new Promise()` hinting about code that actually doesn't exist there (`Error` object in rejection event). This is also not cool, as only promises coming from PouchDB api has these 4 versions available (2x`then` + 2x`catch`).

### Veredict

We need a different interface than the native(or provided) `Promise`, we need an interface that `implements` the native one. It's currently (https://github.com/fredgalvao/pouchdb.d.ts/commit/a0ca47c85eb814e60693678c25e283398ea2a9f3) called `GlobalPromise`, but it can certainly improve. The thing is, **we cannot output code on the global `Promise` name**.

**Comment by AGBrown** [comment]
I was definitely thinking of the [declaration merging](http://www.typescriptlang.org/Handbook#declaration-merging) approach, i.e. `interface Promise<T> {pouchCode;}` rather than `interface Promise<T> extends Promise<T>`.

So if I understand correctly the main objection to this would be that if `Promise` has not been supplied by a user reference externally, then we are defining `Promise` ourselves, and so suggesting that the user does not need to reference a definition file for Promises. Is that correct?

_Side notes:_
- We could name it `PouchPromise` instead of `GlobalPromise` to avoid possible conflicts with other libraries - `GlobalPromise` seems like a name other libs might use?
- We could also move the `GlobalPromise` interface inside the pouchdb module to avoid global namespace clashes?
- We should probably export the `GlobalPromise` to allow people to modify it if they want to?

**EDIT** input from irc://freenode#typescript

> <kbd>[16:30:06] &lt;enlight></kbd> I'm thinking merging this into the standard Promise won't be too bad.
> <kbd>[16:39:58] &lt;enlight></kbd> AndyBrown: I'd probably just put the Promise overloads into a separate d.ts and call it a day.
> <kbd>[16:41:35] &lt;AndyBrown></kbd> enlight: So you would: (1) declaration merge (i.e. just do `interface Promise<R> { ... overloads ... }` and/or (2) in a separate d.ts the user can import if they want?
> <kbd>[16:43:05] &lt;enlight></kbd> Both: 1 and 2

**Comment by fredgalvao** [comment]
My main objection to merging declarations with the standard `Promise` is because we would make intellisense and tsc believe that all Promise objects have a rejection callback that receives a pouch Error object as parameter, and that's not true at all. Only promises generated inside pouch's API can be guaranteed to offer that object.
That's why I would prefer creating `PouchPromise extends Promise` instead of merging declarations.

I also think that moving `PouchPromise` inside pouchdb.async is a good thing, and exporting it is another good idea.

**So**, I can:
- Rename `GlobalPromise` to `PouchPromise`
- Move it inside `module pouchdb.async`
- Export it

What do you think?

**Comment by AGBrown** [comment]
> we would make intellisense and tsc believe that all Promise objects have a rejection callback that receives a pouch Error object as parameter, and that's not true at all

Agreed. If a user goes ahead and uses both pouchdb.d.ts and another d.ts inside their project which also uses promises (e.g. `acl.d.ts`), we don't want the pouchdb overloads showing up when they do `.returnsAPromise().then(...`

Other than that, that plan of action seems to be the right one.

**Comment by AGBrown** [comment]
So a recap following gitter discussion:
1. Rename the `interface Promise` to something else
2. Rename `GlobalPromise` to `PouchPromise` and:
- Move it inside module pouchdb.async
- Export it
- Make every `PouchPromise` method call return and understand native `Promise`s, not `PouchPromises`, so we don't cascade unsafe typings.

This was as a result of the discussion we had about the fact that a `catch` will only certainly receive a `pouchdb.async.Error` if used immediately on the pouch method/ctor (ditto for the `then`s `onRejected` argument). Therefore continually returning a `Thenable` <sup>†</sup>, as `Thenable` did, is misleading. Of the options (including don't hint at all about a pouch error shape; return a `PouchPromise` from `then/catch`; try and return `Error | any` - which doesn't work well) the best option was to just return a `Promise` from the `then`/`catch`.

<sup>†</sup> _`Thenable` was always a bad name anyway, but that was due to point (1)_
