### ISSUE TITLE
Upgrade to TS 1.6, es6 mode, and create tsconfig.json to standardise build process

### ISSUE THREAD

**Issue by AGBrown** [AGBrown/pouchdb.d.ts#24]
Relates to #18. We have to add a `tsconfig.json` to standardise the build process, upgrade to TS1.6 (and fix resulting errors) and set es6 mode.

@fredgalvao has already added a `tsconfig.json` in [fredgalvao/pouchdb.d.ts/486bf85](fredgalvao/pouchdb.d.ts/commit/486bf85). This is just an issue to track and merge that particular task into master.

**Comment by AGBrown** [comment]
@fredgalvao - I'm attempting to separate this (hopefully small) task from the larger work in the PR for #18 (mostly to make the commit history easier to follow, and that PR easier to review and merge). 

I cherry picked your commits from the PR that deal with `tsconfig.json` (and therefore `.gitignore` and `package.json`. You can see the result in [compare dev@34b50edc: i24-tsconfig.json@3726e6bc](https://github.com/AGBrown/pouchdb.d.ts/compare/34b50edc4681f9d4bd378a5d3cf5b0433e723616...3726e6bc6f76cdb61f3ec1fff837033202f7dd6b).

I then noticed two things when using VSCode to build.
1. Having the js files beside the ts files clutters the project view a lot - it feels like the js files belong elsewhere.
2. The files in `\tests` were not building.

To try and address this I added to `tsconfig.json` to send the js transpiled output to `\out`, and changed tsconfig to use an `exclude` instead of `files`. I know you've already tried this so it feels a little like going backwards.

Do you see an issue with the two changes listed above (i24-tsconfig.json@e9e346d4)?

**Comment by fredgalvao** [comment]
I see none. Although I was trying something different with my version of `tsconfig.json`, you achieved the same and something else (the compilation of `tests/**/*.ts`).

I don't quite remember the small issues I encountered that made me go back to `files` instead of `exclude`, but it should come up quicky once I apply your changes on my end.

For now you can consider this closed, I guess.

**Comment by AGBrown** [comment]
@fredgalvao 

> For now you can consider this closed, I guess.

I wish! The change to es6 has resulted in a plague of red wiggly lines and travis failures [in the PR](https://github.com/AGBrown/pouchdb.d.ts/pull/25).

**Comment by AGBrown** [comment]
red lines now fixed (see #26) by pulling in commits from @fredgalvao. #25 open for comments, review, +1 etc. That PR also includes fix for #26.
