### ISSUE TITLE
TypeScript 2.0 Contribution

### ISSUE THREAD

**Issue by filionf** [AGBrown/pouchdb.d.ts#42]
Hello,

I started using the npm types functionnality of TypeScript 2.0 and noticed PouchDB was there. I've started this project to add what is missing for me, but I would like to contribute back: https://github.com/filionf/pouchdb.tsd.2.

What I've done needs more fine-tuning, but do you have any recommendations for posting it back before I clone the DefinitelyTyped tree and send PRs?

**Comment by AGBrown** [comment]
@filionf I believe the [geppy fork](https://github.com/geppy/pouchdb.d.ts) is the current up to date version in DT. It is worth asking on the [slack channel](https://pouchdb.slack.com/messages/typescript/) to see what the current protocol for contribs is as I don't think geppy has opened a PR to merge his changes back into here, so this repo is way behind what DT is currently using.

**Comment by filionf** [comment]
Thanks. I will have a look on slack.
The types-2.0 is a little different from this repo, but I thought you were the originator.
If you want to have a look:
- https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/pouchdb
- https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/pouchdb-core

**Comment by geppy** [comment]
Sorry.  I just commented in the Slack channel that it might be worth replacing this repo with a README that explains the design and that the files are in DT.  I can submit a PR with the latest files here if you'd like, though.

**Comment by geppy** [comment]
My repo isn't even the latest, other people have contributed PRs directly to DT.

**Comment by geppy** [comment]
My repo isn't even the latest, other people have contributed PRs directly to DT.

**Comment by AGBrown** [comment]
> replacing this repo with a README that explains the design and that the files are in DT.

@geppy - potentially that makes this repo redundant, would it not be better to delete it altogether?

**Comment by geppy** [comment]
@AGBrown I was thinking people in Slack might end up here via links, and also that the approach I took to modularization+augmentation might need to be spelled out for people who don't write lots of typing files.  Also, we can use your idea of having actual tests that we run, but have DT as a submodule or a subtree.
